### ISSUE TITLE
Find house numbers with extensions when the number without extension does not exist

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#252]
This use case is reproduced with another database than BAN.
Consider that `66 A RUE DES BONNETS 59200 TOURCOING` is indexed but not `66 RUE DES BONNETS 59200 TOURCOING`

When searching `66 RUE DES BONNETS 59200 TOURCOING`, only the street is found: 

```
  {
    "name": "RUE DES BONNETS",
    "hexacleStreet": "5959922269",
    "id": "Q1RQMjUwNjVTVFAxNDQ1NDA3",
    "label": "RUE DES BONNETS 59200 TOURCOING",
    "postcode": "59200",
    "context": "59, Nord, Hauts-de-France",
    "citycode": "59599",
    "type": "street",
    "score": 0.8338842953532195,
    "city": "TOURCOING"
}
```

It would be great to propose the existing house numbers of the street:

```
  {
    "name": "66 A RUE DES BONNETS",
    "hexacleStreet": "5959922269",
    "label": "66 A RUE DES BONNETS 59200 TOURCOING",
    "id": "Q1RQMjUwNjVTVFAxNDQ1NDA3",
    "context": "59, Nord, Hauts-de-France",
    "type": "housenumber",
    "score": 0.9259740238065844,
    "street": "RUE DES BONNETS",
    "hexacleNumber": "59599246EH",
    "city": "TOURCOING",
    "postcode": "59200",
    "citycode": "59599",
    "housenumber": "66 A"
  }
```

**Comment by gdrouet** [comment]
Hi,

any update on this? Is it something we can manage with addok or should we make sure that we always have in our database a housenumber without extension?

**Comment by yohanboniface** [comment]
I understand that this can be a bit more user friendly in some situations, but I'm not sure this is generic enough to be in addok core.
It can be fixed with either a custom INDEXER or a custom RESULT_PROCESSOR.
Basically, you need to either extend or add a new RESULT_PROCESSOR like https://github.com/addok/addok-france/blob/master/addok_france/utils.py#L160 that would loop a bit more when no matching housenumber is found.
Ping me if you need a bit more details.
