### ISSUE TITLE
Search filter for cities

### ISSUE THREAD

**Issue by kaelhem** [addok/addok#267]
It will be great to be able to filter results for cities like Paris or Lyon (with many sub-districts, so many postcodes).
Actually tested something like this : 
```
http://devapi-adresse.data.gouv.fr/search/?q=1%20av%20daumesnil&postcode=75011,75012,75013&type=housenumber
```
on dev etalab servers (devapi), but it seems that's not the way to proceed : it works great with 2 given postcodes, but with 3 or more, results become strange.

The best thing I can imagine (without any idea of the complexity implied), will be to filter by the city attribute (&city=paris), or something like the revelant part of the postcode (&postcode=75)

Does it sounds possible/ugly/useless? Did I missed something?

**Comment by yohanboniface** [comment]
Isn't that #227?

**Comment by kaelhem** [comment]
It's complementary I think!
Like I said in my comment, the fix in #227 is not very useful for this need.

**Comment by yohanboniface** [comment]
You cannot use multivalues on filters.
#227 is about **indexing** multivalues for filters. So every street of Paris with have both the arrondissemnt citycode AND the Paris citycode. So you can search with the Paris citycode if you want to include all arrondissements.
But AFAIK the data does not yet contain those multivalues.

**Comment by kaelhem** [comment]
Yeah, it will be great if there were one Paris citycode fore every arrondissement... Unfortunatly, it's not the case!

Can you please reopen ?

**Comment by yohanboniface** [comment]
> Can you please reopen ?

This is tracked in #227. :)

**Comment by yohanboniface** [comment]
And BTW, for data topics, best thing is to open an issue on https://github.com/etalab/ban-data/ :)

**Comment by kaelhem** [comment]
Ok ok...
It's not an issue with data. It's a missing feature of the API.
Anyway, 2 closed topics are not very helpful...

So, there is no solution to restrict searches on Paris ? (or another city with arrondissement??)

**Comment by yohanboniface** [comment]
>  It's not an issue with data. It's a missing feature of the API.

Seems we are not understanding each other. :/
It may be me but:

- the API now allows to **index** multiple value for a filter
- so one can index both the arrondissement and Paris citycodes
- so then it becomes possible to filter a search with Paris citycode (so all streets in Paris are candidates)
- but this needs both citycodes to be in the data, thus in ban data

Makes sense?

**Comment by kaelhem** [comment]
I'm sure we are near to understand each other, but this need some more explanations :)

> the API now allows to index multiple value for a filter

You mean, that we are now able to filter with both citycode and postalcode? In this case, I was misunderstood the doc (as I though it was already the case before!).

> so one can index both the arrondissement and Paris citycodes / so then it becomes possible to filter a search with Paris citycode

Sorry but I'm confused with this part. Do you mean that the values entered in the field "citycode" of the ban database is incorrect? In this case, yes, I'm not writing at the right place!

thanks for your time :)

**Comment by yohanboniface** [comment]
So, what you want do to is to restrict your search to Paris data, right?
Something like "Hey addok, please search for 'avenue Daumesnil' anywhere in Paris", correct?

You are right in thinking that this needs a filter, to restrict the search.

What you are trying to do is to filter on multiple **postcodes**: ?postcode=1,2,3, which is **not possible**; and will not become possible soon (check #165 for that topic).

What you need, is a unique value that would embrace all Paris, i.e. all subcities.

This is where citycode and #227 comes into the scene.
Since #227 (actually since 68de11f44aaceb1ec6444541bcbfcbf00bf7f0d7), it's now possible to **index** multiple values for a given filter.

(Note: it's important not to confuse **index** time and **search** time.)

So what does that means: that means that a single document (say "avenue Daumesnil") can have multiple values for a single filter, for example: 75112 (which is the 12th arrondissement) and 75056 (which is Paris). So someone fitltering with "75112" will find "avenue daumesnil", and same for someone filtering with for "75056", which would be your use case.

But those two values **must be in the data**. Thus, as stated [here](https://github.com/addok/addok/issues/227#issuecomment-281610307), after the next data reload, this *should* be the case.

Thus, when the data will have been changed and reloaded, you will be able to do something like:

    search/?q=avenue daumesnil&citycode=75056

And you search will search on all Paris data, only Paris data.

Makes more sense?

**Comment by kaelhem** [comment]
Waoo, everything became clear now!
So, I understand why you redirected me on ban-data repo! Ok, thanks a lot :)
