### ISSUE TITLE
Useful addins to document ?

### ISSUE THREAD

**Issue by EtienneArbogast** [addok/addok#294]
Hi,
shouldn't `https://github.com/Mapotempo/addok-search2steps` and `https://github.com/Mapotempo/addok-postcode_usage_name_BAN_FR` be mentionned in the plugins page of the documentation ?
Imo, these are quite useful addins to be used with French opendata addresses.

**Comment by yohanboniface** [comment]
@EtienneArbogast nice suggestion.
Though I'm not sure those plugin are up to date with Addok 1.0.0, do they?
We can give a hand if needed.

**Comment by EtienneArbogast** [comment]
@yohanboniface : following the specific installation guidelines (git clone in the addok/bin dir), they seem to work fine with the latest version of addok. Especially search2steps, with a little modification in the proposed config file.

**Comment by davidbgk** [comment]
@EtienneArbogast I really doubt about that given that it still uses Werkzeug instead of Falcon and doesn't take advantage of the newly introduced plugin architecture. The [path to the update](http://addok.readthedocs.io/en/latest/changelog/) is not that big but still.

@frodrigo do not hesitate to ask for help if you need to.

**Comment by frodrigo** [comment]
Yes, still in 0.5. But it's in my plan to switch to 1.0.0 some sunny day.

**Comment by jdesboeufs** [comment]
I close since it's an old issue.
If you have plugins compatible with `1.x` addok versions feel free to make a PR to reference th.

**Comment by frodrigo** [comment]
Yes the plugins are now compatible with 1.0
