### ISSUE TITLE
Master-slave redis cluster

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#308]
Hi,

I have a server hosting a slave node in `Redis`.
I deployed on the same host `Addok` which connects to `localhost` when I run `addok shell`.
I'm suprised that a `SEARCH` writes to the node: `READONLY You can't write against a read only slave.`
What `Addok` is trying to write?

Second question is: how to specify both masters and slaves groups to `Addok`? Is it capable to select the master node for write operations?

**Comment by yohanboniface** [comment]
> What Addok is trying to write?

Addok uses tmp keys from time to time for storing set intersections.

Do you have other services using this Redis cluster? If not, easy path is to deactivate replication after import.

> Second question is: how to specify both masters and slaves groups to Addok? Is it capable to select the master node for write operations?

Nope. Addok at this time only connects to the instance you give to. Depending on the replication time, it may work or not to distribute writes and reads differently. Because when it creates a tmp key, it will read it right away (for another intersection), and then delete it.

**Comment by gdrouet** [comment]
I would like to avoid operations as much as possible. Would it work to just turn off the `slave-read-only` flag?

**Comment by yohanboniface** [comment]
> I would like to avoid operations as much as possible.

Not sure what you mean by that :)

> Would it work to just turn off the slave-read-only flag?

Never tested myself, but I don't see why it shouldn't. Let us know :)

Also, take care of your persistence setting: you basically should disable persistence after import, otherwise this can use a lot of CPU. See http://addok.readthedocs.io/en/latest/redis/

**Comment by gdrouet** [comment]
I mean that I would like that ops just run `addok batch` when they need to import a new data set and don't have to pre/post configure `Redis`.

Thanks for the quote about persistence settings. I let you know how it works with `slave-read-only`.

**Comment by gdrouet** [comment]
Yes you're right :-)

**Comment by gdrouet** [comment]
You can close this issue, turning off `slave-read-only` works well.

**Comment by yohanboniface** [comment]
Cool, thanks for the feedback :)
