### ISSUE TITLE
_id should not be returned in results

### ISSUE THREAD

**Issue by cquest** [addok/addok#322]
This new field is internal to addok and should not be returned to avoid confusing with the "id" field.
It caused at least a bug to some API user.

**Comment by davidbgk** [comment]
### Problems

* we display the `id` at the root element of a `Feature` (might raise an issue if no `id` is present here)
* we display both `id` and `_id` within `properties`

It is confusing because our internal `_id` is in use to issue the `GET` against `/get/<_id>`

### Propositions

1. remove the GET endpoint completely as suggested by #254 and do not display our internal `_id` at all
2. do not expose/display `id` anymore but only rely on our internal `_id`

### Thoughts

Proposition 1 is the easiest but is the current `GET` in use? Proposition 2 may be surprising to the user who loaded ids and cannot find them anymore.

**Comment by yohanboniface** [comment]
> is the current GET in use?

It's not documented, so I'd say no.

I'm in favor of moving the /get in a plugin, mainly because if we want to use source id (vs internal _id) this needs a mapping table (so RAM/storage consumption), same if we want to handle housenumbers ids, plus I think /get is not a core need.

**Comment by lgrd** [comment]
Bonjour, 

Justement, je me demandais si on pouvait retrouver une adresse par son id (et non _id). C'est un besoin lorsque l'on a plusieurs applications qui traitent avec les adresses d'une base commune. 

D'où ma question, avez-vous gardé la route /get dans un plugin ?

**Comment by yohanboniface** [comment]
> D'où ma question, avez-vous gardé la route /get dans un plugin ?

Nope, comme on n'a pas le besoin nous-mêmes et que jusqu'ici personne n'avait signalé le besoin, il n'est jamais arrivé sur la pile des trucs à faire.
C'est pas très compliqué à implémenter, mais ça va consommer de la RAM.
Si tu pythonnes, je peux te donner les billes pour le faire; sinon je peux essayer de m'y coller, mais ça sera pas avant mi-juin vu d'ici.

**Comment by lgrd** [comment]
Noté pour la RAM !
Pour le dev, je pense que tu seras plus rapide que moi. Fais comme tu veux ;)
En tout cas, merci pour tes réponses et ton aide !
