### ISSUE TITLE
Call to addok-csv without multipart: possibility, advantages?

### ISSUE THREAD

**Issue by ThomasG77** [addok/addok#331]
The serie 0.5.x was managing multipart. I've seen with the addition of https://github.com/yohanboniface/falcon-multipart/ by @yohanboniface, the behaviour for 1.0 has remained the same.

I want to know if it's possible to send CSV as a streamed content by removing the middleware falcon-multipart? In this case, how do you make the call from client? I've some difficulty to figure out how.

This question is related to the fact I've my own Addok instance on a server and I was wondering if a streamed call would be better for performance.

PS: Forgot to write in English, change question to English...

**Comment by jdesboeufs** [comment]
It's old but I give you an answer and I will close.

Current implementation in `addok-csv` bufferize the input file. Streaming will have no benefit since the server will wait for entire file to be available.

You should run you process by chunk.
You can look at https://github.com/livingdata-co/addok-geocode-stream which handle streaming for you.
