### ISSUE TITLE
QUERY_PROCESSORS_PYPATHS the right to do ?

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#365]
I having trouble cleaning the queries.

Unlike other plugin or code, I need tofdo this, but why?
```pyhton
def clean_query(q):
  q = str(q[0])
  q = re.sub(r'mur ', '', q, flags=re.IGNORECASE)
  q = re.sub(r'grille ', '', q, flags=re.IGNORECASE)
  q = re.sub(r'face ', '', q, flags=re.IGNORECASE)
  q = re.sub(r'angle ', '', q, flags=re.IGNORECASE)
  return [addok.helpers.text.ascii(q)]
```
and
```pyhton
def clean_query(q):
  q = str(q) # Hack, why I need this ?
  q = re.sub(r'\bb\.? ?p\.? ?[\d]*', '', q, flags=re.IGNORECASE) # Orverload
  q = re.sub(r'\bc\.? ?s\.? ?[\d]*', '', q, flags=re.IGNORECASE) # Orverload
  q = re.sub('\(.*?\)', '', q, flags=re.IGNORECASE)
  return q
```

**Comment by yohanboniface** [comment]
You certainly are missing the `@yielder` decorator.
See https://github.com/addok/addok-france/blob/master/addok_france/__init__.py#L13 for example.

All the processors are generators, meaning they are consuming a "stream" and returning a "stream", this for looping only once, and because any processor in the pipeline could return less or more elements than received (for example imagine a processor that would automatically join "saint" and the following word, so "saint onge" and "saintonge" will both work).

In the addok-france example, the decorator is only used on the ``__init__.py`` file, which is one exposed as plugin, to make the function easier to unit test.

Concretely you have three options:

```
@yielder
def myfunc(oneitem):
    dosomething(oneitem)
    return oneitem
```

```
def _myfunc(oneitem):
    dosomething(oneitem)
    return oneitem

myfunc = yielder(_myfunc)
```

```
def myfunc(allitems):
    for oneitem in allitems:
        dosomething(oneitem)
        yield oneitem
```

I understand this may not be very intuitive at first, but it make pipeline speedy (only one loop) while allowing for returning uneven elements.
