### ISSUE TITLE
use the filter postcode with an CEDEX postcode value

### ISSUE THREAD

**Issue by Valentino-Houessou** [addok/addok#396]
I am working on an addresses base which is filled by the users. So the addresses don't follow any standard. I want to use https://adresse.data.gouv.fr/api to get the coordinates. 
To get the most accurate response i am using "postcode" filter. But unfortunately i have some CEDEX postcodes and the api don't  supply any response for the CEDEX postcode.

For exemple : 'https://api-adresse.data.gouv.fr/search/?q=46 BIS RUE DES HAUTS PAVES&postcode=44021' qurey, with  44021 an CEDX codepost don't get any feature.

Is it an other way to proceed? It is possible for the API to handle those requests?

**Comment by yohanboniface** [comment]
The instance at data.gouv.fr does not contain the CEDEX data. AFAIK it's not in open data.

You can buy the data from La Poste and install your own Addok [instance](http://addok.readthedocs.io/en/latest/tutorial/).

Otherwise just re-issue a request when the one with CEDEX does not return any result. If you reuse the same connection, it will be very fast.

**Comment by Valentino-Houessou** [comment]
Thanks for your answer
