### ISSUE TITLE
Housenumber not found when address is not well formatted

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#406]
The housenumber is not found when searching `wasquehal château blanc 7`: https://api-adresse.data.gouv.fr/search/?q=wasquehal%20ch%C3%A2teau%20blanc%207

If we search `7 château blanc wasquehal` everything is fine.

**Comment by yohanboniface** [comment]
This is by design (per [addok-france](https://github.com/addok/addok-france/blob/master/addok_france/utils.py#L106) implementation): allowing a housenumber to be anywhere in the string, search like "rue du 8 Mai" will always return the housenumber 8.
So basically, in the current implementation, a housenumber must be followed by a street type to be retained.
