### ISSUE TITLE
"Weird" result for reverse geocoding with 0, 0

### ISSUE THREAD

**Issue by jbelien** [addok/addok#505]
Hi,

I'm building PHPUnit test for my [PHP Geocoder provider](https://github.com/geo6/geocoder-php-addok-provider) and I discovered that if I make a reverse geocoding on coordinates 0, 0, I have the following result :

<https://api-adresse.data.gouv.fr/reverse/?lat=0&lon=0>

```json
{
    "features": [
        {
            "properties": {
                "distance": 0,
                "name": "baninfo",
                "context": "20181021T232517",
                "id": "db",
                "type": "info",
                "label": "baninfo",
                "score": 1.0
            },
            "type": "Feature",
            "geometry": {
                "coordinates": [
                    0.0,
                    0.0
                ],
                "type": "Point"
            }
        }
    ],
    "version": "draft",
    "limit": 1,
    "type": "FeatureCollection",
    "attribution": "BAN",
    "licence": "ODbL 1.0"
}
```

What is the goal of this result ?
It's quite unexpected to have a result for a reverse geocoding in the middle of the sea ...

Thanks.

**Comment by Flaburgan** [comment]
hi @jbelien, this result is not related to addok, it is contained in the BAN database. I don't know **why** they did that, I guess to have the licence / version info inside the file, but it had to be formatted as an address to avoid parsing problem, or maybe to be able to access the licence / version from addok. I can't tell either if it's safe or not for you to remove it from the `.json` file. I think it doesn't hurt to be kept, so that's what I did.

**Comment by yohanboniface** [comment]
Hack "the papa way"™
@cquest is it still needed? :)

**Comment by cquest** [comment]
This hack could move to another location ;)
The idea is to access metadata with type=info in the query

Currently, other kind of weird results are returned by https://api-adresse.data.gouv.fr/reverse/?lat=0&lon=0&limit=10

This comes from the data, not from addok itself.
