### ISSUE TITLE
return arrondissement in reverse geocoding

### ISSUE THREAD

**Issue by freyfogle** [addok/addok#538]
I am wondering if there is a way to also return the arrondissement in the reverse geocoding response?
Currently the region and departement are returned, but not arrondissement. How do I also get the arrondissement?

Apologies if this is covered in the documentation, I can't seem to find anything relevant. 

Thanks for your help.

**Comment by cquest** [comment]
This is not directly addok related.
Region and departement are returned by addok because they are present (or not) in the json data imported into addok.
Arrondissement info could be added to the json data (or any other field) and addok will return them in the results.
You can pre-process the json data before importing them into addok if you want additional fields.
